[package]
name = "pngmin"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
byteorder = "1.5.0"
crc32fast = "1"
zopfli = "0.8"
flate2 = "1.1.8"
aes-gcm = "0.10.3"
rand = "0.9.2"
clap = { version = "4", features = ["derive"] }
indicatif = "0.18"
argon2 = "0.5"